# Generated by Django 4.2.16 on 2024-09-09 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_book_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='clients',
        ),
        migrations.AddField(
            model_name='libraryclient',
            name='books',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.book'),
        ),
    ]
